language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install ".[tests]"
# command to run tests
script:
  - pytest --cov=h4cktools
# query codecov.io  
after_success:
  - bash <(curl -s https://codecov.io/bash)
